# Generated by Django 4.0.6 on 2022-07-12 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refueling',
            name='date_field',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
