# Generated by Django 4.0.6 on 2022-07-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_refueling_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refueling',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
