# Generated by Django 4.0.6 on 2022-07-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_refueling_amount_alter_refueling_liters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refueling',
            name='date_field',
        ),
        migrations.AlterField(
            model_name='refueling',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refueling',
            name='liters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refueling',
            name='price_per_liter',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
