# Generated by Django 4.0.6 on 2022-07-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_refueling_date_field_alter_refueling_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refueling',
            name='liters',
        ),
        migrations.AddField(
            model_name='refueling',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
